am/config/routes.rb
Am::Application.routes.draw do

  resources :sessions, :only => [:new, :create, :destroy]
  resources :people,        :controller => 'people',    :type => 'person'
  resources :admins,        :controller => 'people',    :type => 'admin'
  resources :users,         :controller => 'people',    :type => 'user'

  resources :personalgroups

  resources :rights

  resources :groups

  resources :comments, :only => [:create, :index, :new]

  resources :videoitems do
      resources :comments, :only => [:create, :index, :new]
  end

  match '/signin',          :to     => 'sessions#new',          :via => 'get'
  match '/sessions',        :to     => 'sessions#create',       :via => 'post'
  match '/signout',         :to     => 'sessions#destroy',      :via => 'delete'

  root 'sessions#new'

end

am/app/views/layouts/_header.html.erb
    <div id="wrapper">
          <!-- Sidebar -->
          <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" <%= link_to '4AM Video', videoitems_path %> </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">

              <!-- Navigation Bar -->
              <%= render :partial => 'shared/navigation' %>

              <ul class="nav navbar-nav navbar-right navbar-user">
                <% if right_in_current_person_personalgroup?('Upload') %>
                        <li class="dropdown alerts-dropdown">
                            <li><%= link_to 'Upload', new_videoitem_path %></li>
                        </li>
                <% else %>
                    <% if current_person_groups_enable? %>
                            <% if right_in_current_person_groups?('Upload') %>
                                <li class="dropdown alerts-dropdown">
                                    <li><%= link_to 'Upload', new_videoitem_path %></li>
                                </li>
                            <% end %>
                    <% end %>
                <% end %>

                <li class="dropdown user-dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_person.type.upcase%> <%= current_person.lastname  %> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Profile', current_person %></li>
                    <li class="divider"></li>
                    <li><%= link_to 'Edit Profile', edit_person_path(current_person) %></li>
                    <li class="divider"></li>
                    <li> <%= link_to 'Sign out', signout_path, method: 'delete' %> </li>
                  </ul>
                </li>
              </ul>
            </div>
          </nav>
    </div><!-- /#wrapper -->


<!--
<li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
<li class="divider"></li>
<li><a href="#"><i class="fa fa-power-off"></i> Log Out</a></li>
-->

am/app/views/layouts/_signin.html.erb
<div class="span8 offset3">

<% provide(:title, 'Sign in') %>

    <% if flash[:error] %>
        <div id="error_explanation">
          <ul>
            <%= flash[:error] %>
          </ul>
        </div>
    <% end %>

    <h1>Sign in</h1>
    <div class="row">
      <div class="span6 offset3">
        <%= form_for(:session, url: sessions_path) do |f| %>
            <%= f.label :email %><br>
            <%= f.text_field :email %><br>
            <%= f.label :password %><br>
            <%= f.password_field :password %><br>
            <%= f.submit 'Sign in', class: 'btn btn-large btn-primary' %>
        <% end %>
      </div>
    </div>

</div>

am/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>4am Video</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <% if signed_in? %>
        <%= render :partial => 'layouts/header' %>
        <div id="wrapper">
            <%= yield %>
        </div>
    <% else %>
      <% render 'layouts/signin' %>
      <div id= "page-wrapper">
        <%= yield %>
      </div>
    <% end %>

</body>

</html>