am/config/routes.rb
Am::Application.routes.draw do

  resources :sessions, :only => [:new, :create, :destroy]
  resources :people,        :controller => 'people',    :type => 'person'
  resources :admins,        :controller => 'people',    :type => 'admin'
  resources :users,         :controller => 'people',    :type => 'user'

  resources :personalgroups

  resources :rights

  resources :groups

  resources :comments, :only => [:create, :index, :new]

  resources :videoitems do
      resources :comments, :only => [:create, :index, :new]
  end

  match '/signin',          :to     => 'sessions#new',          :via => 'get'
  match '/sessions',        :to     => 'sessions#create',       :via => 'post'
  match '/signout',         :to     => 'sessions#destroy',      :via => 'delete'

  root 'sessions#new'

end

am/app/models/personalgroup.rb
class Personalgroup < ActiveRecord::Base

  belongs_to :person
  has_and_belongs_to_many :rights, :join_table => 'personal_groupsrights'

  #Add right to personalgroup
  def add_right_to_personalgroup(right)
      self.rights << right
  end
end

am/app/controllers/personalgroups_controller.rb
class PersonalgroupsController < ApplicationController
  before_action :set_personalgroup, only: [:show, :edit, :update, :destroy]


  # GET /personalgroups
  # GET /personalgroups.json
  def index
    @personalgroups = Personalgroup.all
  end

  # GET /personalgroups/1
  # GET /personalgroups/1.json
  def show
  end

  # GET /personalgroups/new
  def new
    @personalgroup = Personalgroup.new
  end

  # GET /personalgroups/1/edit
  def edit
  end

  # POST /personalgroups
  # POST /personalgroups.json
  def create
    @personalgroup = Personalgroup.new(personalgroup_params)

    respond_to do |format|
      if @personalgroup.save
        format.html { redirect_to @personalgroup, notice: 'Personalgroup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @personalgroup }
      else
        format.html { render action: 'new' }
        format.json { render json: @personalgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personalgroups/1
  # PATCH/PUT /personalgroups/1.json
  def update
    respond_to do |format|
      if @personalgroup.update(personalgroup_params)
        format.html { redirect_to @personalgroup, notice: 'Personalgroup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @personalgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personalgroups/1
  # DELETE /personalgroups/1.json
  def destroy
    @personalgroup.destroy
    respond_to do |format|
      format.html { redirect_to personalgroups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_personalgroup
      @personalgroup = Personalgroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personalgroup_params
      params.require(:personalgroup).permit(:person_id, rights_attributes: [:id, :name, :is_available, :right_ids])
    end
end

am/app/helpers/personalgroups_helper.rb
module PersonalgroupsHelper
end

am/app/views/personalgroups/_form.html.erb
<%= form_for(@personalgroup) do |f| %>
  <% if @personalgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personalgroup.errors.count, "error") %> prohibited this personalgroup from being saved:</h2>

      <ul>
      <% @personalgroup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.text_field :person_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

am/app/views/personalgroups/edit.html.erb
<h1>Editing personalgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @personalgroup %> |
<%= link_to 'Back', personalgroups_path %>

am/app/views/personalgroups/index.html.erb
<h1>Listing personalgroups</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @personalgroups.each do |personalgroup| %>
      <tr>
        <td><%= personalgroup.person %></td>
        <td><%= link_to 'Show', personalgroup %></td>
        <td><%= link_to 'Edit', edit_personalgroup_path(personalgroup) %></td>
        <td><%= link_to 'Destroy', personalgroup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personalgroup', new_personalgroup_path %>

am/app/views/personalgroups/new.html.erb
<h1>New personalgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', personalgroups_path %>

am/app/views/personalgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @personalgroup.person %>
</p>

<%= link_to 'Edit', edit_personalgroup_path(@personalgroup) %> |
<%= link_to 'Back', personalgroups_path %>