am/config/routes.rb
Am::Application.routes.draw do

  resources :sessions, :only => [:new, :create, :destroy]
  resources :people,        :controller => 'people',    :type => 'person'
  resources :admins,        :controller => 'people',    :type => 'admin'
  resources :users,         :controller => 'people',    :type => 'user'

  resources :personalgroups

  resources :rights

  resources :groups

  resources :comments, :only => [:create, :index, :new]

  resources :videoitems do
      resources :comments, :only => [:create, :index, :new]
  end

  match '/signin',          :to     => 'sessions#new',          :via => 'get'
  match '/sessions',        :to     => 'sessions#create',       :via => 'post'
  match '/signout',         :to     => 'sessions#destroy',      :via => 'delete'

  root 'sessions#new'

end

am/app/models/videoitem.rb
class Videoitem < ActiveRecord::Base

    has_many :comments , :dependent => :destroy
    accepts_nested_attributes_for :comments, :reject_if => lambda { |attribute| attribute[:message].blank?}, :allow_destroy => true

    has_many :assets , :dependent => :destroy
    accepts_nested_attributes_for :assets, :allow_destroy => true

    belongs_to :person

end

am/app/controllers/videoitems_controller.rb
class VideoitemsController < ApplicationController
  before_action :set_videoitem, only: [:show, :edit, :update, :destroy]
  before_filter :signed_in_person

  # GET /videoitems
  # GET /videoitems.json
  def index
    @videoitems = Videoitem.all
  end

  # GET /videoitems/1
  # GET /videoitems/1.json
  def show
      @videoitem.increment!(:views)
      @videoitem = Videoitem.find(params[:id])
      @owner = Person.find_by_id(@videoitem.person_id)
      @new_comment = @videoitem.comments.build
  end

  # GET /videoitems/new
  def new
    @videoitem = Videoitem.new
    @new_image = @videoitem.assets.build
  end

  # GET /videoitems/1/edit
  def edit
      @new_image = @videoitem.assets.build
  end

  # POST /videoitems
  # POST /videoitems.json
  def create
    #@videoitem = Videoitem.new(videoitem_params)
    #@videoitem.views = 0

    #@videoitem = @person.videoitems.new(videoitem_params)
    @videoitem = current_person.videoitems.new(videoitem_params)
    @videoitem.views = 0

    respond_to do |format|
      if @videoitem.save
        format.html { redirect_to @videoitem, notice: 'Videoitem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @videoitem }
      else
        format.html { render action: 'new' }
        format.json { render json: @videoitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videoitems/1
  # PATCH/PUT /videoitems/1.json
  def update
    respond_to do |format|
      if @videoitem.update(videoitem_params)
        format.html { redirect_to @videoitem, notice: 'Videoitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @videoitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videoitems/1
  # DELETE /videoitems/1.json
  def destroy
    @videoitem.destroy
    respond_to do |format|
      format.html { redirect_to videoitems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_videoitem
      @videoitem = Videoitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def videoitem_params
      params.require(:videoitem).permit(:title, :description, :is_available, :date, :views, :pathvideo,
                                        comments_attributes: [:id, :message, :is_available, :date, :url_for, :_destroy],
                                        assets_attributes: [:id, :image, :_destroy])
    end
end

am/app/helpers/videoitems_helper.rb
module VideoitemsHelper
end

am/app/views/videoitems/_form.html.erb
<%= form_for(@videoitem, :html => {:multipart => true}) do |f| %>
  <% if @videoitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@videoitem.errors.count, "error") %> prohibited this videoitem from being saved:</h2>

      <ul>
      <% @videoitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :placeholder => 'Title' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, :placeholder => 'Description' %>
  </div>
  <div class="field">
    <%= f.label :is_available %><br>
    <%= f.check_box :is_available %>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>

  <% if !(f.object.present?) %>
    <div class="field">
        <%= f.label :views %><br>
        <%= f.number_field :views %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pathvideo %><br>
    <%= f.text_field :pathvideo, :placeholder => 'Path Video'  %>
  </div>

  <div class="field">
    <%= f.fields_for :assets do |asset| %>
        <% if asset.object.new_record? %>
            <%= asset.label :'Add new image' %><br>
            <%= asset.file_field :image %><br>
        <% end %>
    <% end %>
  </div>

  <div class="field">
    <% if !(f.object.new_record?) %>
    <div class="assetsVideo">
      <ul>
            <%= f.label :'Videos images' %><br>
            <%= f.fields_for :assets do |asset| %>
                <% unless asset.object.new_record? %>
                    <li>
                        <%= link_to image_tag(asset.object.image.url(:thumb)),
                                              asset.object.image.url(:original) %><br>
                        <%= asset.label :'delete'%>
                        <%= asset.check_box :_destroy %><br>
                    </li>
                <% end %>
            <% end %>
      </ul>
    </div>
  <% end %>
  </div>


    <div class="field">
    <%= f.fields_for :comments do |builder| %>
        <%= builder.label :message, 'Add Comment' %><br>
        <%= builder.text_area :message, :row => 3, :readonly => true %><br>
        <% unless builder.object.new_record? %>
            <%= builder.label :'delete'%>
            <%= builder.check_box :_destroy %>
            <%= builder.label :'available' %>
            <%= builder.check_box :is_available %><br>
        <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

am/app/views/videoitems/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Edit Video <small>Editing video</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Editing video </li>
      </ol>
    </div>
  </div>

  <%= render 'form' %>

  <%= link_to 'Show', @videoitem, class:'btn btn-default' %>
  <%= link_to 'Back', videoitems_path, class:'btn btn-default' %>
</div>

am/app/views/videoitems/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Myvideos <small>List videos</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Myvideos </li>
      </ol>
    </div>
  </div>

  <div class="containerLine">
    <% @videoitems.each do |videoitem| %>
        <% if videoitem.is_available? %>
            <ul class="containervideo">
              <li class="videoitem">
                <div class="imagevideo">
                  <%= link_to( image_tag( videoitem.assets.first.image.url(:thumb),
                                          title: videoitem.title,
                                          alt:   videoitem.title,
                                          size:  '175x98'), videoitem)
                  %>
                </div>

                <div class="containerTitle">
                  <div class="title">
                    <%= link_to(videoitem.title, videoitem) %>
                  </div>

                  <div class="titlecontainer">
                    <div>
                      By: <% @owner = Person.find_by_id(videoitem.person_id) %> <%= @owner.lastname.upcase %> <%= @owner.firstname %>
                    </div>
                    <div>
                        Views: <%= videoitem.views %>
                    </div>
                  </div>

                  <% if current_person.type == 'Admin' %>
                      <div class="adminAction">
                          <%= link_to 'Edit', edit_videoitem_path(videoitem) %>
                          <%= link_to 'Destroy', videoitem, method: :delete, data: { confirm: 'Are you sure?' } %>
                      </div>
                  <% end %>
                </div>
              </li>
            </ul>
        <% end %>
    <% end %>
  </div>

  <%#= link_to('Upload', new_video_item_path) %>

</div>

am/app/views/videoitems/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Upload Video <small>Upload Video</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Upload Video </li>
      </ol>
    </div>
  </div>

  <%= render 'form' %>
  <%= link_to 'Back', videoitems_path, class:'btn btn-default' %>
</div>

am/app/views/videoitems/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Show Video <small>Show Video</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  Show Video </li>
      </ol>
    </div>
  </div>

  <div class="page">
    <div class="video">
      <div class="header>">
        <div class="headerTitle">
          <strong>Title: </strong>
          <%= @videoitem.title %>
        </div>
        <% if current_person.type == 'Admin' %>
            <div class="headerEdit">
                <%= link_to 'Edit Video', edit_videoitem_path(@videoitem) %>
            </div>
        <% end %>
      </div>

      <div class="videocontainer">
        <div class="player">
          <%= video_tag([@videoitem.pathvideo], :size => '640x387', :controls => true, :preload => 'none', :autoplay => true) do%>
              Your browser does not support the video tag.
          <% end %>
        </div>
      </div>

      <div class="content">
        <div class="contentInfo">

          <div class="description">
            <p>
              <strong>Description:</strong>
              <%= @videoitem.description %>
            </p>
            <p>
              <strong>Uploaded on:</strong>
              <%= @videoitem.date %>
            </p>
            <p>
              <strong>Views:</strong>
              <%= @videoitem.views %>
            </p>

            <p>
              <strong>Owner:</strong>
              <i><%= @owner.lastname.upcase %></i>
              <%= @owner.firstname %>
            </p>
          </div>

          <div class="options">
            <% Right.all.each do |right| %>
                <% if right.name != 'Comment' && right.name != 'Upload'%>
                  <al>
                    <% if right_in_current_person_personalgroup?(right.name) %>
                        <%= link_to right.name, '#', :alt => right.name %> |
                  <% else %>
                        <% if current_person_groups_enable? %>
                            <% if right_in_current_person_groups?(right.name) %>
                                <%= link_to right.name, '#', :alt => right.name %> |
                            <% end %>
                        <% end %>
                    <% end %>
                  </al>
                <% end %>
            <% end %>
          </div>
        </div>

        <% if right_in_current_person_personalgroup?('Comment') %>
            <p>
              <%= form_for([@videoitem, @new_comment], :url => videoitem_comments_path(@videoitem, @new_comment)) do |f| %>
                  <%= f.text_area :message, size:'89x3', class:'form-control' %><br>
                  <%= f.submit 'Post Comment', class:'btn btn-default' %>
              <% end %>
            </p>
        <% else %>
            <% if current_person_groups_enable? %>
                <% if right_in_current_person_groups?('Comment') %>
                    <p>
                      <%= form_for([@videoitem, @new_comment], :url => videoitem_comments_path(@videoitem, @new_comment)) do |f| %>
                          <%= f.text_area :message, size:'89x3', class:'form-control' %><br>
                          <%= f.submit 'Post Comment', class:'btn btn-default' %>
                      <% end %>
                    </p>
                <% end %>
            <% end %>
        <% end %>

          <div class="comments">
            <strong>All Comments: </strong>
            <% if @videoitem.comments.size != 0 %>
                <ol>
                  <% @videoitem.comments.each  do |comment| %>
                      <% if comment.is_available? %>
                      <li>
                        <%= comment.message %><br>
                        <% if !(comment.person_id.nil?) %>
                            <% owner = Person.find_by_id(comment.person_id)%>
                            <%#= owner.lastname.upcase+' '+owner.firstname %>
                            <%= link_to owner.lastname.upcase+' '+owner.firstname, owner %>
                      <% end %>
                      </li>
                      <% end %>
                  <% end %>
                </ol>
            <% else %>
                No comments
            <% end %>
          </div>
        </div>
      </div>
    </div>
    </div>

</div>