am/config/routes.rb
Am::Application.routes.draw do

  resources :sessions, :only => [:new, :create, :destroy]
  resources :people,        :controller => 'people',    :type => 'person'
  resources :admins,        :controller => 'people',    :type => 'admin'
  resources :users,         :controller => 'people',    :type => 'user'

  resources :personalgroups

  resources :rights

  resources :groups

  resources :comments, :only => [:create, :index, :new]

  resources :videoitems do
      resources :comments, :only => [:create, :index, :new]
  end

  match '/signin',          :to     => 'sessions#new',          :via => 'get'
  match '/sessions',        :to     => 'sessions#create',       :via => 'post'
  match '/signout',         :to     => 'sessions#destroy',      :via => 'delete'

  root 'sessions#new'

end

am/app/views/shared/_navigation.erb
<ul class="nav navbar-nav side-nav">

  <!--
  <li class="active"><a href="index.html"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  <li><a href="tableFiles.html"><i class="fa fa-table"></i> Table Files</a></li>
  <li><a href="upload.html"><i class="fa fa-edit"></i> Upload</a></li>
  <li><a href="download.html"><i class="fa fa-file"></i> Download</a></li>
  <li><a href="videos.html"><i class="fa fa-desktop"></i> Videos</a></li>
  <li><a href="images.html"><i class="fa fa-desktop"></i> Images</a></li>
  <li><a href="tables.html"><i class="fa fa-table"></i> Table Users</a></li>
  <li><a href="settingsProfile.html"><i class="fa fa-gear"></i> Settings Profile</a></li>
   -->

  <li><%= link_to 'Videos', videoitems_path, :alt => 'videos' %></li>
  <% if current_person.type == Person::TYPES[0] %>
      <li><%= link_to 'Rights',rights_path, :alt => 'rights' %></li>
      <li><%= link_to 'Groups', groups_path, :alt => 'groups' %></li>
      <!-- <li><%#= link_to 'Management', 'management', :alt => 'management' %></li> -->
      <li><%= link_to 'Users', people_path,  :alt => 'users' %></li>
      <li><%= link_to 'Send Video', '#' ,:alt => 'sendvideo'%></li>
      <!-- AJOUTER PARTIE PATH -->
  <% end %>

</ul>